const { EmbedBuilder } = require('discord.js');

module.exports = {
  name: 'ramal',
  description: 'Meramal nasibmu atau orang lain dengan gaya wibu 🔮',
  execute(message, args) {
    const target = message.mentions.users.first() || message.author;
    const name = target.username;

    const ramalan = [
      'Hari ini kamu akan bertemu waifu impianmu... di mimpi.',
      'Gacha kamu hari ini: 0, dompet kamu: -300k.',
      'Waifumu bilang dia suka kamu... di universe paralel.',
      'Kamu akan push rank... lalu uninstall game-nya.',
      'Hari ini kamu akan mencintai waifu baru. Lagi.',
      'Opening anime yang kamu ulang-ulang akhirnya bosan sama kamu.',
      'Dompetmu hari ini: RIP karena preorder figure.',
      'Ada energi positif dari waifu... sayangnya cuma hologram.',
      'Kamu akan mengulang anime favoritmu... untuk ke-12 kalinya.',
      'Hari ini kamu akan dighosting oleh waifu AI-mu.',
      'Waifumu akan tersenyum padamu... dari layar monitor.',
      'Kamu akan dipanggil “senpai”... oleh bot Discord.',
      'Hari ini kamu akan memanggil karakter anime dengan "istriku". Lagi.',
      'Kamu akan merasa spesial... karena jadi top 1 simp waifu.',
      'Seseorang akan jatuh cinta padamu... setelah kamu stop ngepost waifu tiap hari. Tapi kamu nggak akan berhenti.',
      'Kamu akan merasa produktif... lalu binge-watching 18 episode nonstop.',
      'Waifumu hadir... di dakimakura yang baru datang.',
      'Kamu akan membaca doujin... demi riset yang sangat ilmiah.',
      'Hari ini kamu akan berargumen soal best girl... di kolom komentar YouTube.',
      'Kamu akan dimarahi ibu karena teriak "YAMETE!" jam 3 pagi.',
      'Otaku points kamu naik... tapi reputasi sosialmu turun.',
      'Waifumu akan menemanimu tidur malam ini... via screensaver.',
      'Hari ini kamu akan menonton anime... lalu overthinking hidupmu.',
      'Kamu akan makan sambil nonton anime... dan tersedak pas adegan sedih.',
      'Dompetmu akan berkata: "Kenapa figure-nya harus limited?"',
      'Hari ini kamu akan menang giveaway... tapi zonk.',
      'Kamu akan disukai seseorang... tapi dia 2D.',
      'Cosplay impianmu akan datang... di paket COD yang belum dibayar.',
      'Hari ini kamu akan dapat spoiler... dan pura-pura lupa.',
      'Waifumu akan gacha kamu balik... dan skip.',
      'Kamu akan jadi MC... di kehidupan orang lain.',
      'Hari ini kamu akan menonton anime, membaca manga, main gacha, dan tetap kesepian.',
      'Kamu akan bahagia hari ini... setelah nonton anime wholesome. Lalu nangis.',
      'Kamu akan menganggap NPC sebagai waifu.',
      'Hari ini kamu akan debat soal power scaling anime.',
      'Kamu akan merasa hidup... saat waifumu tersenyum di AMV.',
      'Kamu akan tertidur... ditemani OST anime favoritmu.',
      'Seseorang akan kirim kamu meme wibu... dan kamu merasa dimengerti.',
      'Hari ini kamu akan mimpi nikah sama karakter anime. Lagi.',
      'Kamu akan pakai kaos anime... dan bangga.',
      'Waifumu akan "pingsan"... karena kamu lupa charging HP.',
      'Kamu akan membeli keychain waifu... dan kehilangannya minggu depan.',
      'Kamu akan tertawa... pas baca komentar fansub Indo.',
      'Hari ini kamu akan nyanyi OP anime... dan salah nada.',
      'Waifumu akan nyemangatinmu... lewat soundboard bot.',
      'Kamu akan nonton anime ecchi... lalu buru-buru alt+tab.',
      'Kamu akan pakai wallpaper waifu... dan ditanya: “Itu siapa?”',
      'Hari ini kamu akan nonton anime... dengan subtitle bahasa alien.',
      'Kamu akan ikut event Jejepangan... dan pulang dengan pin waifu.',
      'Hari ini kamu akan maraton anime... sampai subuh.',
      'Kamu akan nonton anime baru... lalu skip opening karena nggak sabar.',
      'Kamu akan ke warung... tapi pakai jaket anime.',
      'Waifumu akan bilang “ganbatte!” padamu... dalam ringtone.',
      'Kamu akan merasa magis... saat gacha dapet dupe.',
      'Hari ini kamu akan nostalgia... anime lawas yang tayang di TV lokal.',
      'Kamu akan beli merch waifu... lalu pura-pura bilang "hadiah buat teman".',
      'Waifumu akan muncul... di notifikasi sound efek HP.',
      'Kamu akan latihan jadi VA... lalu sadar suara kamu cempreng.',
      'Hari ini kamu akan push gacha... dan hanya dapat 3 bintang.',
      'Kamu akan simpan gambar waifu... di folder "tugas".',
      'Kamu akan cerita ke waifumu... dan dia hanya tersenyum dari poster.',
      'Kamu akan merasa disukai... setelah nonton anime harem.',
      'Hari ini kamu akan membela waifu-mu... di forum perang waifu.',
      'Kamu akan kirim stiker anime... dan dibilang aneh.',
      'Hari ini kamu akan bikin quote anime... dan posting jam 2 pagi.',
      'Kamu akan bangga... setelah bikin tier list waifu sendiri.',
      'Kamu akan browsing doujin... dan nggak jadi karena cover-nya serem.',
      'Hari ini kamu akan pasang banner anime... di profil Discord.',
      'Waifumu akan tersipu... kalau kamu upgrade kualitas headset.',
      'Kamu akan nonton anime di ruang keluarga... pas adegan "ehm" muncul.',
      'Kamu akan hafal nama karakter... tapi lupa deadline tugas.',
      'Waifumu hari ini akan... tidak menghubungimu. Seperti biasa.',
      'Kamu akan denger lagu anime... lalu flashback kehidupan.',
      'Kamu akan bilang “kawaii~” ke kucing tetangga.',
      'Hari ini kamu akan buat fanfic... dan delete karena malu.',
      'Kamu akan ngaku otaku... lalu pura-pura cool di depan umum.',
      'Waifumu akan datang... dalam bentuk figma chibi.',
      'Kamu akan merasa dilihat... oleh poster anime di kamarmu.',
      'Hari ini kamu akan bicara bahasa Jepang random... di Indomaret.',
      'Kamu akan buka anime... dan baru sadar udah 5 jam nonton.',
      'Waifumu akan menyapamu... lewat mimpi siang.',
      'Hari ini kamu akan merasa penting... karena dikasih role “Wibu Elit”.',
      'Kamu akan gacha SR... padahal pengen SSR.',
      'Kamu akan merasa kesepian... tapi tetap bilang "Im fine".',
      'Waifumu akan muncul... saat kamu buka YouTube rekomendasi.',
      'Kamu akan ketawa... pas baca komen “no context anime scene”.',
      'Kamu akan jadi MC... tapi bukan di anime, di grup kelas.',
      'Hari ini kamu akan buka VN... dan nangis karena ending-nya sad.',
      'Kamu akan chatting waifumu... di AI bot waifu simulator.',
      'Waifumu akan ngambek... karena kamu suka karakter lain.',
      'Kamu akan nonton anime slice of life... dan merasa hidupmu lebih hambar.',
      'Hari ini kamu akan duduk termenung... sambil lihat fanart waifu-mu.',
      'Kamu akan browsing fanart... dan nyesel buka NSFW di ruang publik.',
      'Waifumu akan bangga padamu... kalau kamu mandi dulu.',
      'Hari ini kamu akan ingat... quote anime yang bikin kamu semangat lagi.',
    ];

    const hasil = ramalan[Math.floor(Math.random() * ramalan.length)];

    const embed = new EmbedBuilder()
      .setTitle(`🔮 Ramalan Hari Ini`)
      .setDescription(`**${name}**, ${hasil}`)
      .setColor(0xaa00ff)
      .setFooter({ text: 'Ramalan ini tidak disetujui oleh waifu-mu' })
      .setTimestamp();

    message.channel.send({ embeds: [embed] });
  }
};